spring:
  datasource:
    url: jdbc:mysql://xuyutech.top:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: index1130
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid配置项，默认spring-boot不支持，故需要config类来解析
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    database: 0           # Redis数据库索引（默认为0）
    #    host: 199.199.3.95    # Redis服务器地址
    host: 127.0.0.1
    port: 6379            # Redis服务器连接端口
    password: zpds20152015 # Redis服务器连接密码（默认为空）
    timeout: 10000        # 连接超时时间（毫秒）
    jedis:
      pool:
        max-idle: 200
        max-wait: 10000
        max-active: 1024

#mybatis:
#  type-aliases-package: com.example.demo.entity

mybatis-plus:
  type-aliases-package: com.example.demo.entity
#  mapUnderscoreToCamelCase: false


#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:com/mingyue/cloud/mapper/*.xml
#  type-aliases-package: com.mingyue.cloud.entity

# 日志
logging:
  config: classpath:logback.xml

#自定义
mq:
  name-server: 192.168.1.115:9876
  instance-name: cluster-1
  retry-times: 2
  producer:
    groups:
      - pg_test_01
    topics:
      - p_test_01
      - p_test_02
  consumer:
    groups:
      - cg_test_01
      - cg_test_02
    topics:
      - p_test_01
      - p_test_02
    tags:
      - '*'
      - '*'

# es
elasticsearch:
  max-connect-total: 50
  max-connect-per-route: 10
  connection-request-timeout-millis: 500
  socket-timeout-millis: 30000
  connect-timeout-millis: 1000
  schema: http
  nodes:
#    - localhost:9200
#    - 172.16.10.108:9200
    - 192.168.1.115:9200

